spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/
zuul:
  routes:
    author-service:
      path: /author-service/**
      serviceId: author-service
    book-service:
      path: /book-service/**
      serviceId: node-sidecar
